<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SubjectsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $subjects = [
            ['id'=> 'SUA101', 'name_ar'=> 'لغة عربية (1)', 'name_en'=> 'Arabic (1)'],
            ['id'=> 'SUE101', 'name_ar'=> 'لغة انجليزية (1)', 'name_en'=> 'English (1)'],
            ['id'=> 'SUI100', 'name_ar'=> 'ثقافة إسلامية', 'name_en'=> 'Islami Culture'],
            ['id'=> 'MAT101', 'name_ar'=> 'حساب التفاضل والتكامل (1)', 'name_en'=> 'Calculus (1)'],
            ['id'=> 'SUConf', 'name_ar'=> 'الصراع العربي الاسرائيلي', 'name_en'=> 'Israeli-Arabic Conflict'],
            ['id'=> 'CCS111', 'name_ar'=> 'برمجة الحاسوب (1)', 'name_en'=> 'Computer Programming (1)'],
            ['id'=> 'CCS100', 'name_ar'=> 'مهارات الحاسوب', 'name_en'=> 'Computer Skills'],
            ['id'=> 'SUA102', 'name_ar'=> 'لغة عربية (2)', 'name_en'=> 'Arabic (2)'],
            ['id'=> 'SUE102', 'name_ar'=> 'لغة انجليزية (2)', 'name_en'=> 'English (2)'],
            ['id'=> 'MAT110', 'name_ar'=> 'حساب التفاضل والتكامل (2)', 'name_en'=> 'Calculus (2)'],
            ['id'=> 'MAT111', 'name_ar'=> 'رياضيات متقطعة', 'name_en'=> 'Discrete Mathematics'],
            ['id'=> 'CCS110', 'name_ar'=> 'أساسيات علوم الحاسوب', 'name_en'=> 'CS Fundamentals'],
            ['id'=> 'SUNC', 'name_ar'=> 'الثقافة الوطنية', 'name_en'=> 'National Culture'],
            ['id'=> 'CS201', 'name_ar'=> 'برمجة الحاسوب (2)', 'name_en'=> 'Computer Programming (2)'],
            ['id'=> 'MAT201', 'name_ar'=> 'مبادئ الاحصاء والاحتمالات', 'name_en'=> 'Principles of Probablilities and Statistics'],
            ['id'=> 'CCS203', 'name_ar'=> 'أساسيات قواعد البيانات', 'name_en'=> 'Fundamentals of Database'],
            ['id'=> 'CIT201', 'name_ar'=> 'مبادئ شبكات الحاسوب', 'name_en'=> 'Principles of Computer Networks'],
            ['id'=> 'CIT202', 'name_ar'=> 'أساسيات تكنولوجيا الويب', 'name_en'=> 'Fundamentals of Web Technologies'],
            ['id'=> 'CS202', 'name_ar'=> 'التصميم المنطقي الرقمي', 'name_en'=> 'Digital Logic Design'],
            ['id'=> 'CCS210', 'name_ar'=> 'البرمجة الهدفية الموجهة', 'name_en'=> 'Object-Oriented Programming'],
            ['id'=> 'CCS201', 'name_ar'=> 'برمجة الحاسوب (2)', 'name_en'=> 'Computer Programming (2)'],
            ['id'=> 'CCS214', 'name_ar'=> 'أساسيات نظم التشغيل', 'name_en'=> 'Fundamentals of Operating Systems'],
            ['id'=> 'CCS211', 'name_ar'=> 'هياكل البيانات والخوارزميات', 'name_en'=> 'Data Structures and Algorithms'],
            ['id'=> 'CCS218', 'name_ar'=> 'معمارية وتنظيم الحاسوب', 'name_en'=> 'Computer Architecture and Organization'],
            ['id'=> 'FC210', 'name_ar'=> 'مهارات الاتصال', 'name_en'=> 'Communication Skills'],
            ['id'=> 'CIS210', 'name_ar'=> 'نظم قواعد البيانات', 'name_en'=> 'Database Systems'],
            ['id'=> 'MAT305', 'name_ar'=> 'الجبر الخطي', 'name_en'=> 'Linear Algebra'],
            ['id'=> 'CSW301', 'name_ar'=> 'تطوير تطبيقات الويب', 'name_en'=> 'Web Applications Development'],
            ['id'=> 'CCS301', 'name_ar'=> 'تصميم وتطوير الويب', 'name_en'=> 'Web Design and Development'],
            ['id'=> 'CCS302', 'name_ar'=> 'أمنية الحاسوب', 'name_en'=> 'Computer Security'],
            ['id'=> 'CIS301', 'name_ar'=> 'تحليل وتصميم النظم', 'name_en'=> 'Systems Analysis and Design'],
            ['id'=> 'FC301', 'name_ar'=> 'طرق البحث', 'name_en'=> 'Research Methods'],
            ['id'=> 'MA200', 'name_ar'=> 'جبر خطي', 'name_en'=> 'Linear Algebra'],
            ['id'=> 'CCS305', 'name_ar'=> 'نظرية الحوسبة', 'name_en'=> 'Computational Theory'],
            ['id'=> 'CIT313', 'name_ar'=> 'التفاعل بين الإنسان والحاسوب', 'name_en'=> 'Human-Computer Interaction'],
            ['id'=> 'CCS315', 'name_ar'=> 'الرسم بالحاسوب', 'name_en'=> 'Computer Graphics'],
            ['id'=> 'CCS314', 'name_ar'=> 'مقدمة إلى الذكاء الاصطناعي', 'name_en'=> 'Introduction to Artificial Intelligence'],
            ['id'=> 'CCS312', 'name_ar'=> 'لغات البرمجة المقارنة', 'name_en'=> 'Comparative Programming Languages'],
            ['id'=> 'IS305', 'name_ar'=> 'مقدمة في هندسة البرمجيات', 'name_en'=> 'Inroduction to Software Engineering'],
            ['id'=> 'CS403', 'name_ar'=> 'بناء المترجمات', 'name_en'=> 'Compilers Construction'],
            ['id'=> 'CCS401', 'name_ar'=> 'البرمجة المتقدمة', 'name_en'=> 'Advanced Programming'],
            ['id'=> 'CIT403', 'name_ar'=> 'اختياري (1)', 'name_en'=> 'Elective (1)'],
            ['id'=> 'CIT404', 'name_ar'=> 'اختياري (2)', 'name_en'=> 'Elective (2)'],
            ['id'=> 'CIT409', 'name_ar'=> 'مشروع التخرج (1)', 'name_en'=> 'Graduation Project (1)'],
            ['id'=> 'CIS401', 'name_ar'=> 'اخلاقيات الحاسوب', 'name_en'=> 'Computer Ethics'],
            ['id'=> 'CIT413', 'name_ar'=> 'اختياري (3)', 'name_en'=> 'Elective (3)'],
            ['id'=> 'CIT414', 'name_ar'=> 'اختياري (4)', 'name_en'=> 'Elective (4)'],
            ['id'=> 'CIT419', 'name_ar'=> 'مشروع التخرج (2)', 'name_en'=> 'Graduation Project (2)'],
            ['id'=> 'CCS412', 'name_ar'=> 'تعقيدات الخورزميات', 'name_en'=> 'Algorithms and Complexity'],
            ['id'=> 'CCS101', 'name_ar'=> 'مقدمة في الحاسوب', 'name_en'=> 'Introduction to Computer'],
            ['id'=> 'CIS110', 'name_ar'=> 'أساسيات نظم المعلومات', 'name_en'=> 'IS Fundamentals'],
            ['id'=> 'CIS101', 'name_ar'=> 'معمارية المؤسسات', 'name_en'=> 'Enterprise Architecture'],
            ['id'=> 'CIS211', 'name_ar'=> 'إدارة أعمال', 'name_en'=> 'Business Management'],
            ['id'=> 'CCS303', 'name_ar'=> 'أمنية المعلومات', 'name_en'=> 'Information Security'],
            ['id'=> 'CIS302', 'name_ar'=> 'تطوير التطبيقات', 'name_en'=> 'Application Development'],
            ['id'=> 'CIS305', 'name_ar'=> 'المحاسبة', 'name_en'=> 'Accounting'],
            ['id'=> 'CIS311', 'name_ar'=> 'تحليل وتصميم النظم المتقدم', 'name_en'=> 'Advanced Systems Analysis and Design'],
            ['id'=> 'CIS317', 'name_ar'=> 'الأعمال الألكترونية', 'name_en'=> 'E-Business'],
            ['id'=> 'CIS313', 'name_ar'=> 'أساسيات إدارة المشاريع', 'name_en'=> 'Fundamentals of Project Management'],
            ['id'=> 'CIS314', 'name_ar'=> 'إدارة واستراتيجيات نظم المعلومات', 'name_en'=> 'IS Strategy and Management'],
            ['id'=> 'CIS312', 'name_ar'=> 'تنقيب البيانات', 'name_en'=> 'Data Mining'],
            ['id'=> 'CIS402', 'name_ar'=> 'نظم المعلومات الجغرافية', 'name_en'=> 'Geographic Information System'],
            ['id'=> 'CIS411', 'name_ar'=> 'إدارة قواعد البيانات', 'name_en'=> 'Database Administration'],
            ['id'=> 'CIT110', 'name_ar'=> 'أساسيات تقنية المعلومات', 'name_en'=> 'IT Fundamentals'],
            ['id'=> 'NT300', 'name_ar'=> 'مبادئ شبكات الحاسوب', 'name_en'=> 'Principles of Computr Networks'],
            ['id'=> 'IT201', 'name_ar'=> 'ادارة عامة', 'name_en'=> 'General Management'],
            ['id'=> 'CIT210', 'name_ar'=> 'إدارة البيانات والمعلومات (1)', 'name_en'=> 'Data and Information Management (1)'],
            ['id'=> 'CIT211', 'name_ar'=> 'تكنولوجيا الويب', 'name_en'=> 'Web Technologies'],
            ['id'=> 'FAC201', 'name_ar'=> 'مهارات الاتصال', 'name_en'=> 'Communiation Skills'],
            ['id'=> 'CITs100', 'name_ar'=> 'إدارة مشاريع تكنولوجيا المعلومات', 'name_en'=> 'IT Project Management'],
            ['id'=> 'CS204', 'name_ar'=> 'البرمجة الهدفية', 'name_en'=> 'Object-Oriented Programming'],
            ['id'=> 'CIT301', 'name_ar'=> 'إدارة البيانات والمعلومات (2)', 'name_en'=> 'Data and Information Management (2)'],
            ['id'=> 'CIT302', 'name_ar'=> 'البرمجة التكاملية', 'name_en'=> 'Integrative Programming'],
            ['id'=> 'CIT303', 'name_ar'=> 'البرمجة المرئية', 'name_en'=> 'Visual Programming'],
            ['id'=> 'CIT300', 'name_ar'=> 'إدارة مشاريع تكنولوجيا المعلومات', 'name_en'=> 'IT Project Management'],
            ['id'=> 'CIT315', 'name_ar'=> 'إدارة أمنية المعلومات', 'name_en'=> 'Information Security Management'],
            ['id'=> 'CIT310', 'name_ar'=> 'إدارة شبكات الحاسوب', 'name_en'=> 'Computer Networks Administration'],
            ['id'=> 'CIT311', 'name_ar'=> 'إدارة تكنولوجيا المعلومات', 'name_en'=> 'IT Management'],
            ['id'=> 'CIT400', 'name_ar'=> 'إدارة وصيانة الأنظمة', 'name_en'=> 'Systems Administration and Maintenance'],
            ['id'=> 'CS407', 'name_ar'=> 'النظم الموزعة والمتوازية', 'name_en'=> 'Parallel and Distributed Systems'],
            ['id'=> 'UNIVE1', 'name_ar'=> 'لغة انجليزية (1)', 'name_en'=> 'English (1)'],
            ['id'=> 'UNIVA1', 'name_ar'=> 'لغة عربية (1)', 'name_en'=> 'Arabic (1)'],
            ['id'=> 'MA101', 'name_ar'=> 'حساب التفاضل والتكامل (1)', 'name_en'=> 'Calculus (1)'],
            ['id'=> 'CS103', 'name_ar'=> 'برمجة الحاسوب (1)', 'name_en'=> 'Computer Programming (1)'],
            ['id'=> 'CY001', 'name_ar'=> 'اساسيات امن سيبراني', 'name_en'=> 'Fundamentals of Cyber Security'],
            ['id'=> 'NT202', 'name_ar'=> 'شبكات الحاسوب (1)', 'name_en'=> 'Computer Networks (1)'],
            ['id'=> 'IS302', 'name_ar'=> 'امنية المعلومات', 'name_en'=> 'Information Security'],
            ['id'=> 'NT301', 'name_ar'=> 'شبكات الحاسوب (2)', 'name_en'=> 'Computer Networks (2)'],
            ['id'=> 'CYS200', 'name_ar'=> 'مقدمة الى لينكس', 'name_en'=> 'Introduction to Linux'],
            ['id'=> 'TM11501881', 'name_ar'=> 'منهجية بحث', 'name_en'=> 'Research Methodology'],
            ['id'=> 'TM11501877', 'name_ar'=> 'قواعد بيانات متقدم', 'name_en'=> 'Advanced Database Systems'],
            ['id'=> 'TM165032', 'name_ar'=> 'مواضيع مختارة في نظم المعلومات', 'name_en'=> 'Selected Topics in Information Systems'],
            ['id'=> 'TM165033', 'name_ar'=> 'تحليلات النظم والاعمال', 'name_en'=> 'Systems & Business Analytics'],
            ['id'=> 'TM165034', 'name_ar'=> 'امن وتدقيق نظم المعلومات', 'name_en'=> 'Information Systems Security and Audit'],
            ['id'=> 'TM11502078', 'name_ar'=> 'ذكاء الاعمال', 'name_en'=> 'Business Intelligence'],
            ['id'=> 'TM165035', 'name_ar'=> 'التحول الرقمي', 'name_en'=> 'Digital Transformation'],
            ['id'=> 'TM11501884', 'name_ar'=> 'الحوسبة السحابية', 'name_en'=> 'Cloud Computing'],
            ['id'=> 'TM11501880', 'name_ar'=> 'بناء برمجيات', 'name_en'=> 'Software Construction'],
            ['id'=> 'TM165045', 'name_ar'=> 'امن معلومات', 'name_en'=> 'Information Security'],
            ['id'=> 'TM11501882', 'name_ar'=> 'الذكاء الاصطناعي', 'name_en'=> 'Artificial Intelligent'],
            ['id'=> 'TM11501878', 'name_ar'=> 'خوارزميات متقدم', 'name_en'=> 'Advanced Algorithms and Complexity'],
            ['id'=> 'TM165036', 'name_ar'=> 'ذكاء البيانات الضخمة', 'name_en'=> 'Big Data Intelligence'],
            ['id'=> 'TM165037', 'name_ar'=> 'الرؤية الحاسوبية', 'name_en'=> 'Computer Vision'],
            ['id'=> 'TM11502515', 'name_ar'=> 'نمذجة ومحاكاة', 'name_en'=> 'Modeling &Simulation'],
            ['id'=> 'TM11501937', 'name_ar'=> 'مواضيع متقدمة في تكنولوجيا المعلومات', 'name_en'=> 'Advanced Topics in Information Technology'],
            ['id'=> 'TM165041', 'name_ar'=> 'مواضيع اختيارية في الشبكات', 'name_en'=> 'Optional topics in networks'],
            ['id'=> 'TM165047', 'name_ar'=> 'ادارة تكنولوجيا المعلومات', 'name_en'=> 'Information Technology Management'],
            ['id'=> 'TM165043', 'name_ar'=> 'ادارة البيانات المتقدمة', 'name_en'=> 'Advanced Data Management'],
            ['id'=> 'TM165042', 'name_ar'=> 'الحوسبة المنتشرة', 'name_en'=> 'Widespread computing'],
            ['id'=> 'TM165044', 'name_ar'=> 'مواضيع مختارة في الامن السيبراني', 'name_en'=> 'Selected Topics in Cybersecurity'],
            ['id'=> 'TM165040', 'name_ar'=> 'امنية الشبكات', 'name_en'=> 'Network Security'],
            ['id'=> 'TM165038', 'name_ar'=> 'امان الويب والسحابة', 'name_en'=> 'Web and cloud security'],
            ['id'=> 'TM165046', 'name_ar'=> 'اساسيات الامن السيبراني', 'name_en'=> 'Cyber Security Fundamentals'],
            ['id'=> 'TM165039', 'name_ar'=> 'اختبار الاختراق والاستجابة للحوادث', 'name_en'=> 'Penetration Testing and Incident Response'],
        ];

        foreach ($subjects as $subject) {
            \App\Models\Subject::create($subject);
        }

    }
}
